In [112]:
# Part 1: Gradient Boosting

import pandas as pd

#importing features.csv
features = pd.read_csv('_data/data/features.csv', index_col='match_id')
print(features.shape)
features.head(10)

(97230, 108)

,start_time,lobby_type,r1_hero,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,...,dire_boots_count,dire_ward_observer_count,dire_ward_sentry_count,dire_first_ward_time,duration,radiant_win,tower_status_radiant,tower_status_dire,barracks_status_radiant,barracks_status_dire
match_id,,,,,,,,,,,,,,,,,,,,,
0,1430198770,7,11,5,2098,1489,20,0,0,7,...,4,2,2,-52,2874,1,1796,0,51,0
1,1430220345,0,42,4,1188,1033,9,0,1,12,...,4,3,1,-5,2463,1,1974,0,63,1
2,1430227081,7,33,4,1319,1270,22,0,0,12,...,4,3,1,13,2130,0,0,1830,0,63
3,1430263531,1,29,4,1779,1056,14,0,0,5,...,4,2,0,27,1459,0,1920,2047,50,63
4,1430282290,7,13,4,1431,1090,8,1,0,8,...,3,3,0,-16,2449,0,4,1974,3,63
5,1430284186,1,11,5,1961,1461,19,0,1,6,...,4,4,0,-43,1453,0,512,2038,0,63
8,1430293701,1,8,3,967,1136,7,1,0,8,...,6,3,0,10,1968,0,1536,1983,12,63
9,1430299335,7,35,5,2117,1252,16,0,0,6,...,3,4,0,-15,4079,1,1540,0,63,0
11,1430308974,1,17,5,1527,906,10,0,1,7,...,3,4,0,26,3071,0,0,1572,0,63
12,1430316105,7,15,5,1651,1060,14,0,1,10,...,3,2,0,16,2384,0,0,2038,0,63

In [113]:
#filtering out data, related to the outcome of the competition
features_train = features.iloc[:,:102]
print(features_train.shape)
features_train.head(10)

(97230, 102)

,start_time,lobby_type,r1_hero,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,...,radiant_ward_sentry_count,radiant_first_ward_time,dire_bottle_time,dire_courier_time,dire_flying_courier_time,dire_tpscroll_count,dire_boots_count,dire_ward_observer_count,dire_ward_sentry_count,dire_first_ward_time
match_id,,,,,,,,,,,,,,,,,,,,,
0,1430198770,7,11,5,2098,1489,20,0,0,7,...,0,35,103,-84,221,3,4,2,2,-52
1,1430220345,0,42,4,1188,1033,9,0,1,12,...,0,-20,149,-84,195,5,4,3,1,-5
2,1430227081,7,33,4,1319,1270,22,0,0,12,...,1,-39,45,-77,221,3,4,3,1,13
3,1430263531,1,29,4,1779,1056,14,0,0,5,...,0,-30,124,-80,184,0,4,2,0,27
4,1430282290,7,13,4,1431,1090,8,1,0,8,...,0,46,182,-80,225,6,3,3,0,-16
5,1430284186,1,11,5,1961,1461,19,0,1,6,...,1,-27,2,-86,212,4,4,4,0,-43
8,1430293701,1,8,3,967,1136,7,1,0,8,...,2,-35,6,-86,182,3,6,3,0,10
9,1430299335,7,35,5,2117,1252,16,0,0,6,...,1,26,119,-61,NaN,2,3,4,0,-15
11,1430308974,1,17,5,1527,906,10,0,1,7,...,1,9,NaN,-84,226,1,3,4,0,26
12,1430316105,7,15,5,1651,1060,14,0,1,10,...,0,-24,186,-83,195,1,3,2,0,16

In [114]:
#creating vector of target values
targets_train = features.iloc[:,103]
print(targets_train.shape)
targets_train.head(10)

(97230,)

match_id
0     1
1     1
2     0
3     0
4     0
5     0
8     0
9     1
11    0
12    0
Name: radiant_win, dtype: int64

In [115]:
#features with missing data values
features_train.count()[features_train.count() < 97230]

first_blood_time               77677
first_blood_team               77677
first_blood_player1            77677
first_blood_player2            53243
radiant_bottle_time            81539
radiant_courier_time           96538
radiant_flying_courier_time    69751
radiant_first_ward_time        95394
dire_bottle_time               81087
dire_courier_time              96554
dire_flying_courier_time       71132
dire_first_ward_time           95404
dtype: int64

In [116]:
#fill NAs with zeros and check
features_train_filled = features_train.fillna(value = 0)
print(features_train_filled.shape)
features_train_filled.count()[features_train_filled.count() < 97230]

(97230, 102)

Series([], dtype: int64)

In [117]:
#creating cross-validation folds

from sklearn.cross_validation import KFold
from sklearn.cross_validation import cross_val_score

kf = KFold(len(features_train_filled), n_folds=5, shuffle=True, random_state=16)

In [118]:
#learning GradientBoostingClassifier

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_auc_score
import numpy as np
import time
import datetime

scores = np.zeros(3)
ix = 0

for n_trees in [10, 20, 30] :
    
    print("n_trees = ", n_trees)
    clf = GradientBoostingClassifier(n_estimators = n_trees, verbose = True, random_state = 16, learning_rate = 0.1, max_depth = 3)
    
    start_time = datetime.datetime.now()
    cv_scores = cross_val_score(clf, features_train_filled, np.ravel(targets_train), cv = kf, scoring='roc_auc')
    print ('Time elapsed:', datetime.datetime.now() - start_time)
    
    scores[ix] = cv_scores.mean()
    ix = ix + 1
    

print(scores)

n_trees =  10
      Iter       Train Loss   Remaining Time
         1           1.3785            9.04s
         2           1.3730            8.59s
         3           1.3681            7.49s
         4           1.3635            6.29s
         5           1.3588            5.14s
         6           1.3546            4.09s
         7           1.3500            3.04s
         8           1.3459            2.01s
         9           1.3420            0.99s
        10           1.3384            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3785            9.05s
         2           1.3729            8.66s
         3           1.3681            7.37s
         4           1.3633            6.23s
         5           1.3585            5.11s
         6           1.3538            4.05s
         7           1.3494            3.03s
         8           1.3452            2.02s
         9           1.3411            1.01s
        10           1.3373            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3784            8.71s
         2           1.3728            7.81s
         3           1.3677            6.82s
         4           1.3632            5.83s
         5           1.3583            4.81s
         6           1.3536            3.84s
         7           1.3492            2.87s
         8           1.3454            1.92s
         9           1.3413            0.96s
        10           1.3374            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3789            9.06s
         2           1.3732            8.21s
         3           1.3684            7.10s
         4           1.3640            6.01s
         5           1.3594            4.98s
         6           1.3548            3.94s
         7           1.3502            2.94s
         8           1.3458            1.95s
         9           1.3418            0.97s
        10           1.3380            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3783            9.01s
         2           1.3725            8.09s
         3           1.3675            7.06s
         4           1.3629            6.01s
         5           1.3578            4.95s
         6           1.3536            3.96s
         7           1.3493            3.04s
         8           1.3451            2.01s
         9           1.3411            1.00s
        10           1.3373            0.00s
Time elapsed: 0:00:49.977859
n_trees =  20
      Iter       Train Loss   Remaining Time
         1           1.3785           18.36s
         2           1.3730           17.45s
         3           1.3681           16.47s
         4           1.3635           15.55s
         5           1.3588           14.48s
         6           1.3546           13.64s
         7           1.3500           12.66s
         8           1.3459           11.65s
         9           1.3420           10.64s
        10           1.3384            9.64s
        20           1.3087            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3785           18.53s
         2           1.3729           17.76s
         3           1.3681           17.04s
         4           1.3633           16.03s
         5           1.3585           14.84s
         6           1.3538           13.72s
         7           1.3494           12.69s
         8           1.3452           11.66s
         9           1.3411           10.68s
        10           1.3373            9.69s
        20           1.3077            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3784           18.32s
         2           1.3728           17.48s
         3           1.3677           16.62s
         4           1.3632           15.62s
         5           1.3583           14.50s
         6           1.3536           13.49s
         7           1.3492           12.49s
         8           1.3454           11.58s
         9           1.3413           10.59s
        10           1.3374            9.61s
        20           1.3076            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3789           19.04s
         2           1.3732           17.81s
         3           1.3684           16.74s
         4           1.3640           15.65s
         5           1.3594           14.66s
         6           1.3548           13.58s
         7           1.3502           12.52s
         8           1.3458           11.54s
         9           1.3418           10.56s
        10           1.3380            9.56s
        20           1.3080            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3783           20.81s
         2           1.3725           19.10s
         3           1.3675           17.84s
         4           1.3629           16.58s
         5           1.3578           15.27s
         6           1.3536           14.24s
         7           1.3493           13.11s
         8           1.3451           11.97s
         9           1.3411           10.94s
        10           1.3373            9.89s
        20           1.3074            0.00s
Time elapsed: 0:01:36.650528
n_trees =  30
      Iter       Train Loss   Remaining Time
         1           1.3785           28.57s
         2           1.3730           27.61s
         3           1.3681           26.66s
         4           1.3635           25.66s
         5           1.3588           24.52s
         6           1.3546           23.64s
         7           1.3500           22.66s
         8           1.3459           21.60s
         9           1.3420           20.50s
        10           1.3384           19.48s
        20           1.3087            9.69s
        30           1.2887            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3785           28.28s
         2           1.3729           27.37s
         3           1.3681           26.56s
         4           1.3633           25.63s
         5           1.3585           24.41s
         6           1.3538           23.25s
         7           1.3494           22.21s
         8           1.3452           21.27s
         9           1.3411           20.31s
        10           1.3373           19.31s
        20           1.3077            9.59s
        30           1.2879            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3784           28.33s
         2           1.3728           27.48s
         3           1.3677           26.46s
         4           1.3632           25.42s
         5           1.3583           24.26s
         6           1.3536           23.15s
         7           1.3492           22.11s
         8           1.3454           21.37s
         9           1.3413           20.53s
        10           1.3374           19.68s
        20           1.3076            9.70s
        30           1.2874            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3789           28.13s
         2           1.3732           27.43s
         3           1.3684           26.32s
         4           1.3640           25.24s
         5           1.3594           24.33s
         6           1.3548           23.16s
         7           1.3502           22.06s
         8           1.3458           21.00s
         9           1.3418           20.01s
        10           1.3380           18.97s
        20           1.3080            9.84s
        30           1.2875            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3783           27.99s
         2           1.3725           26.94s
         3           1.3675           26.25s
         4           1.3629           25.27s
         5           1.3578           24.10s
         6           1.3536           23.21s
         7           1.3493           22.09s
         8           1.3451           20.99s
         9           1.3411           20.01s
        10           1.3373           18.99s
        20           1.3074            9.41s
        30           1.2874            0.00s
Time elapsed: 0:02:25.996351
[ 0.66452447  0.68143096  0.68895714]

In [119]:
#fit the classifier to the whole train set
clf = GradientBoostingClassifier(n_estimators = 30, verbose = True, random_state = 16, learning_rate = 0.1, max_depth = 3)
clf.fit(features_train_filled, np.ravel(targets_train))

      Iter       Train Loss   Remaining Time
         1           1.3786           40.57s
         2           1.3732           40.84s
         3           1.3681           38.72s
         4           1.3636           37.65s
         5           1.3589           35.66s
         6           1.3547           34.15s
         7           1.3502           32.50s
         8           1.3461           30.84s
         9           1.3422           29.25s
        10           1.3385           28.07s
        20           1.3092           14.03s
        30           1.2892            0.00s

GradientBoostingClassifier(init=None, learning_rate=0.1, loss='deviance',
              max_depth=3, max_features=None, max_leaf_nodes=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=30,
              presort='auto', random_state=16, subsample=1.0, verbose=True,
              warm_start=False)

In [120]:
#check feature importances
importances = np.transpose(np.array([np.ravel(features_train_filled.columns), clf.feature_importances_]))
importances_df = pd.DataFrame(importances, columns = ('feature', 'importance'))
importances_df_sorted = importances_df.sort_values(by = 'importance', ascending=False)
print(importances_df_sorted.head(40))

                         feature   importance
13                       r2_gold    0.0985392
29                       r4_gold    0.0912859
37                       r5_gold    0.0906459
5                        r1_gold     0.087887
45                       d1_gold    0.0857812
77                       d5_gold    0.0836271
53                       d2_gold     0.083617
61                       d3_gold    0.0774292
69                       d4_gold    0.0763788
21                       r3_gold    0.0758817
84           first_blood_player1    0.0553756
90           radiant_boots_count    0.0434079
98              dire_boots_count    0.0356174
88   radiant_flying_courier_time   0.00352072
89        radiant_tpscroll_count   0.00245377
72                     d4_deaths    0.0023739
70                         d4_lh   0.00187251
36                         r5_xp   0.00134181
101         dire_first_ward_time  0.000919184
68                         d4_xp  0.000856406
30                         r4_lh   0.00080055
54                         d2_lh  0.000387265
85           first_blood_player2            0
64                     d3_deaths            0
96      dire_flying_courier_time            0
67                      d4_level            0
66                       d4_hero            0
65                      d3_items            0
97           dire_tpscroll_count            0
63                      d3_kills            0
71                      d4_kills            0
62                         d3_lh            0
99      dire_ward_observer_count            0
60                         d3_xp            0
59                      d3_level            0
58                       d3_hero            0
100       dire_ward_sentry_count            0
95             dire_courier_time            0
94              dire_bottle_time            0
86           radiant_bottle_time            0

In [121]:
#importing features_test.csv
features_test = pandas.read_csv('./_data/data/features_test.csv', index_col='match_id')
print(features_test.shape)
features_test.head(10)

(17177, 102)

,start_time,lobby_type,r1_hero,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,...,radiant_ward_sentry_count,radiant_first_ward_time,dire_bottle_time,dire_courier_time,dire_flying_courier_time,dire_tpscroll_count,dire_boots_count,dire_ward_observer_count,dire_ward_sentry_count,dire_first_ward_time
match_id,,,,,,,,,,,,,,,,,,,,,
6,1430287923,0,93,4,1103,1089,8,0,1,9,...,0,12,247,-86,272,3,4,2,0,118
7,1430293357,1,20,2,556,570,1,0,0,9,...,2,-29,168,-54,NaN,3,2,2,1,16
10,1430301774,1,112,2,751,808,1,0,0,13,...,1,-22,46,-87,186,1,3,3,0,-34
13,1430323933,1,27,3,708,903,1,1,1,11,...,2,-49,30,-89,210,3,4,2,1,-26
16,1430331112,1,39,4,1259,661,4,0,0,9,...,0,36,180,-86,180,1,3,2,1,-33
18,1430334264,0,97,5,2067,1549,15,0,0,8,...,0,243,260,-55,279,3,5,2,0,34
19,1430334995,1,97,4,1862,1487,24,0,1,5,...,0,17,NaN,-84,209,4,3,2,1,-32
24,1430349466,1,106,5,1991,1983,19,2,0,10,...,0,-25,73,-87,NaN,2,5,2,1,-35
33,1430366484,1,57,2,517,500,0,0,1,9,...,1,119,76,-86,237,1,3,2,2,NaN
37,1430375099,7,36,3,1060,691,5,0,0,6,...,0,160,139,-85,NaN,1,2,2,0,-27

In [122]:
#features_test with missing data values
features_test.count()[features_test.count() < 17177]

first_blood_time               13625
first_blood_team               13625
first_blood_player1            13625
first_blood_player2             9411
radiant_bottle_time            14282
radiant_courier_time           17050
radiant_flying_courier_time    12292
radiant_first_ward_time        16847
dire_bottle_time               14335
dire_courier_time              17047
dire_flying_courier_time       12653
dire_first_ward_time           16914
dtype: int64

In [123]:
#fill NAs with zeros and check
features_test_filled = features_test.fillna(value = 0)
print(features_test_filled.shape)
features_test_filled.count()[features_test_filled.count() < 17177]

(17177, 102)

Series([], dtype: int64)

In [124]:
#make predictions for test data
pred = clf.predict_proba(features_test_filled)[:, 1]
print(pred.shape)
pred

(17177,)

array([ 0.48886143,  0.58417438,  0.47399   , ...,  0.31355857,
        0.36404427,  0.51936291])

In [125]:
#create output array and write it to .csv
#output = np.concatenate((np.array([features_test_filled.index.values]), np.array([pred])), axis = 0)
output = np.array([features_test_filled.index.values, pred])
#print(output.shape)
output = np.transpose(output)
print(output.shape)
np.savetxt('output.csv', output, fmt='%.10f', header = 'match_id, radiant_win', delimiter=',')

(17177, 2)

In [134]:
# _____________________________________________________________________________________________________________________________________________________
# Part 2: Logistic Regression
# Scaling features; using features_train_filled from Part 1

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(features_train_filled)
features_train_filled_scaled = scaler.transform(features_train_filled)
print(features_train_filled_scaled.shape)
print(features_train_filled_scaled)

(97230, 102)
[[-2.54436416  1.54068827 -1.24422828 ..., -0.55115386  1.84600409
  -1.12149424]
 [-2.54045236 -0.92779756 -0.29225805 ...,  0.67817009  0.43778816
   0.04394713]
 [-2.53923104  1.54068827 -0.5686365  ...,  0.67817009  0.43778816
   0.49028637]
 ...,
 [ 1.09874571 -0.57515673  1.42743012 ...,  0.67817009  0.43778816
  -0.20401912]
 [ 1.09895204 -0.57515673  1.48884755 ...,  0.67817009  0.43778816
  -0.87352799]
 [ 1.1026479   1.54068827 -0.04658831 ..., -0.55115386 -0.97042777
  -0.79913812]]

In [138]:
# Using cross-validation folds from Part 1 (kf)
# learning linear_model.LogisticRegression 

from sklearn.linear_model import LogisticRegression

scores_lr = np.zeros(5)
ix = 0

for C_reg in [10000, 100, 1, 0.01, 0.0001] :
    
    print("C_reg = ", C_reg)
    clf_lr = LogisticRegression(penalty='l2', C = C_reg, random_state = 16)
    
    start_time = datetime.datetime.now()
    cv_scores_lr = cross_val_score(clf_lr, features_train_filled_scaled, np.ravel(targets_train), cv = kf, scoring='roc_auc')
    print ('Time elapsed:', datetime.datetime.now() - start_time)
    
    scores_lr[ix] = cv_scores_lr.mean()
    ix = ix + 1
    

print(scores_lr)

C_reg =  10000
Time elapsed: 0:00:13.341764
C_reg =  100
Time elapsed: 0:00:13.432768
C_reg =  1
Time elapsed: 0:00:12.943740
C_reg =  0.01
Time elapsed: 0:00:12.142695
C_reg =  0.0001
Time elapsed: 0:00:05.091291
[ 0.71616261  0.71616264  0.71616264  0.7161928   0.7110732 ]

In [253]:
# check coefficients of the resulting model (=importances)

clf_lr = LogisticRegression(penalty='l2', C = 0.01, random_state = 16)
clf_lr.fit(features_train_filled_scaled, np.ravel(targets_train))

print(np.shape(np.ravel(clf_lr.coef_)))
print(np.shape(np.ravel([features_train_filled.columns])))

coef_lr = np.transpose(np.array([np.ravel([features_train_filled.columns]), np.ravel(clf_lr.coef_)]))
coef_lr_df = pd.DataFrame(coef_lr, columns = ('feature', 'coef')); coef_lr_df
coef_lr_df_sorted = coef_lr_df.sort_values(by = 'coef', ascending=False)
print(coef_lr_df_sorted.head(40))

(102,)
(102,)
                         feature        coef
5                        r1_gold    0.225764
13                       r2_gold    0.211589
37                       r5_gold      0.2008
29                       r4_gold    0.190365
21                       r3_gold    0.184642
22                         r3_lh    0.135185
14                         r2_lh    0.134911
30                         r4_lh    0.132379
6                          r1_lh    0.119586
38                         r5_lh    0.114273
28                         r4_xp   0.0800996
4                          r1_xp   0.0702989
20                         r3_xp   0.0588485
36                         r5_xp   0.0576048
12                         r2_xp   0.0553327
0                     start_time    0.048028
41                      r5_items   0.0429956
97           dire_tpscroll_count   0.0419702
25                      r3_items   0.0400812
101         dire_first_ward_time   0.0344242
88   radiant_flying_courier_time   0.0331092
90           radiant_boots_count   0.0308977
94              dire_bottle_time    0.030508
9                       r1_items   0.0292559
33                      r4_items   0.0274011
35                      r5_level   0.0271782
95             dire_courier_time   0.0216506
17                      r2_items   0.0214455
80                     d5_deaths   0.0198703
47                      d1_kills   0.0162156
75                      d5_level   0.0140487
55                      d2_kills   0.0138338
99      dire_ward_observer_count   0.0137214
48                     d1_deaths   0.0120936
59                      d3_level   0.0100516
72                     d4_deaths  0.00945462
56                     d2_deaths  0.00816349
100       dire_ward_sentry_count  0.00794252
82              first_blood_time  0.00771429
11                      r2_level  0.00739036

In [151]:
# drop categorial variables from features_train_filled
# then scale (I know, there's no sense not to work with already scaled data, but that's considered more readable)

features_train_filled_dropped = features_train_filled.drop(['lobby_type', 'r1_hero', 'r2_hero', 'r3_hero', 'r4_hero', 'r5_hero',
                                                            'd1_hero', 'd2_hero', 'd3_hero', 'd4_hero', 'd5_hero'], axis = 1)
print(features_train_filled_dropped.shape)
#print(features_train_filled_dropped.head(10))

scaler_dropped = StandardScaler().fit(features_train_filled_dropped)
features_train_filled_dropped_scaled = scaler_dropped.transform(features_train_filled_dropped)
print(features_train_filled_dropped_scaled.shape)
print(features_train_filled_dropped_scaled)

(97230, 91)
(97230, 91)
[[-2.54436416  1.40080818  1.52597175 ..., -0.55115386  1.84600409
  -1.12149424]
 [-2.54045236  0.50131354 -0.08013929 ...,  0.67817009  0.43778816
   0.04394713]
 [-2.53923104  0.50131354  0.1510701  ...,  0.67817009  0.43778816
   0.49028637]
 ...,
 [ 1.09874571  0.50131354  0.29226667 ...,  0.67817009  0.43778816
  -0.20401912]
 [ 1.09895204 -0.39818111 -0.17368203 ...,  0.67817009  0.43778816
  -0.87352799]
 [ 1.1026479  -0.39818111 -0.31840851 ..., -0.55115386 -0.97042777
  -0.79913812]]

In [152]:
# Using cross-validation folds from Part 1 (kf)
# learning linear_model.LogisticRegression on "dropped" data

scores_lr_dropped = np.zeros(5)
ix = 0

for C_reg in [10000, 100, 1, 0.01, 0.0001] :
    
    print("C_reg = ", C_reg)
    clf_lr_dropped = LogisticRegression(penalty='l2', C = C_reg, random_state = 16)
    
    start_time = datetime.datetime.now()
    cv_scores_lr_dropped = cross_val_score(clf_lr_dropped, features_train_filled_dropped_scaled, np.ravel(targets_train), cv = kf, scoring='roc_auc')
    print ('Time elapsed:', datetime.datetime.now() - start_time)
    
    scores_lr_dropped[ix] = cv_scores_lr_dropped.mean()
    ix = ix + 1
    

print(scores_lr_dropped)

C_reg =  10000
Time elapsed: 0:00:12.050690
C_reg =  100
Time elapsed: 0:00:11.769673
C_reg =  1
Time elapsed: 0:00:11.652667
C_reg =  0.01
Time elapsed: 0:00:11.088634
C_reg =  0.0001
Time elapsed: 0:00:04.759272
[ 0.7161913   0.71619134  0.71619222  0.71622276  0.71106361]

In [185]:
# count unique heros for both counterparts

features_train_filled.loc[:,('lobby_type', 'r1_hero', 'r2_hero', 'r3_hero', 'r4_hero', 'r5_hero',
                                                            'd1_hero', 'd2_hero', 'd3_hero', 'd4_hero', 'd5_hero')].apply(pd.value_counts)

,lobby_type,r1_hero,r2_hero,r3_hero,r4_hero,r5_hero,d1_hero,d2_hero,d3_hero,d4_hero,d5_hero
0,12718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,55962,1199,1080,991,1011,999,1285,1111,1040,1062,1005
2,NaN,581,649,598,624,615,558,583,595,631,611
3,NaN,1058,1075,1095,1186,1102,1005,1100,1117,1084,1112
4,NaN,554,526,509,495,500,543,503,496,526,515
5,NaN,699,796,794,744,825,668,706,734,780,849
6,NaN,461,380,382,357,410,474,400,354,375,372
7,28550,3899,4201,4235,4564,4552,3844,4106,4223,4408,4321
8,NaN,1748,1692,1621,1651,1619,1718,1660,1701,1607,1567
9,NaN,315,268,257,291,278,306,248,232,260,255
10,NaN,157,103,94,105,110,163,117,104,113,119
11,NaN,5045,4128,3885,3609,3499,4030,3493,3250,2988,3023
12,NaN,1057,1032,932,920,986,1074,992,995,957,956
13,NaN,368,318,364,313,295,357,325,336,312,313
14,NaN,329,302,273,280,296,294,259,233,230,258
15,NaN,629,607,546,584,554,685,650,573,628,602
16,NaN,295,330,370,364,353,354,317,386,382,359
17,NaN,924,767,739,745,638,869,758,754,671,740
18,NaN,614,571,539,573,578,649,565,608,542,571
19,NaN,860,759,692,657,654,877,741,687,622,623
20,NaN,821,963,931,951,937,807,906,1014,1028,1002
21,NaN,2533,2433,2338,2240,2241,2678,2479,2417,2309,2312
22,NaN,822,756,772,747,717,883,783,777,677,758
23,NaN,259,209,177,191,177,206,198,166,188,180
25,NaN,2385,2176,2209,2127,2156,2475,2280,2258,2233,2168
26,NaN,1584,1910,1858,2073,2096,1647,1921,1980,2073,2109
27,NaN,515,540,511,656,611,470,551,580,617,558
28,NaN,1688,1980,2020,2014,1959,1853,2051,2058,1942,1970
29,NaN,673,767,770,774,822,667,757,738,791,819
30,NaN,1845,2205,2280,2431,2510,1772,2187,2190,2493,2482
...,...,...,...,...,...,...,...,...,...,...,...
80,NaN,88,69,76,83,59,84,75,77,87,69
81,NaN,345,353,334,320,308,406,362,325,358,320
82,NaN,212,158,175,163,158,187,185,177,130,151
83,NaN,169,172,162,197,179,151,170,186,164,182
84,NaN,618,692,751,794,769,549,683,698,715,745
85,NaN,1965,2073,2221,2377,2306,2070,2385,2325,2268,2401
86,NaN,1595,1706,1718,1840,1757,1556,1657,1696,1768,1671
87,NaN,1542,1630,1827,1839,1902,1549,1745,1691,1877,1924
88,NaN,356,324,382,402,381,319,377,376,382,414
89,NaN,352,292,277,288,265,388,295,271,303,253
90,NaN,238,270,257,271,276,292,276,268,274,294
91,NaN,548,409,380,420,406,509,428,362,433,401
92,NaN,231,245,233,231,231,279,231,245,265,242
93,NaN,865,810,777,793,766,942,811,766,724,762
94,NaN,420,372,403,387,357,471,413,397,380,393
95,NaN,199,190,177,156,163,193,167,165,150,188
96,NaN,427,527,540,556,550,405,541,571,561,533
97,NaN,806,808,821,724,749,832,781,796,748,764
98,NaN,286,359,372,329,318,310,343,322,349,349
99,NaN,999,1052,1017,1064,1103,939,1067,1095,1051,1070
100,NaN,2623,2812,2961,2900,2805,2675,2900,2985,2883,2965
101,NaN,462,499,515,489,534,452,475,539,488,510
102,NaN,327,307,349,344,337,341,346,312,325,306
103,NaN,75,62,83,66,57,77,85,68,80,61
104,NaN,410,390,393,373,365,392,357,354,368,371
105,NaN,159,164,146,136,137,170,148,140,142,141
106,NaN,2128,1900,1781,1706,1713,2207,1911,1789,1725,1831
109,NaN,20,18,17,17,16,30,12,11,19,13
110,NaN,743,854,912,884,859,708,762,862,869,913
112,NaN,3119,3639,3585,3741,3851,3169,3657,3598,3802,3759

In [230]:
# мешок слов
# N — количество различных героев в выборке 
# на самом деле нет, различных 108, но они пронумерованы до 112, поэтому необходимо использовать N = 112

N = 112
X_pick = np.zeros((features_train_filled.shape[0], N))

for i, match_id in enumerate(features_train_filled.index):
    for p in range(5):
        X_pick[i, features_train_filled.ix[match_id, 'r%d_hero' % (p+1)]-1] = 1
        X_pick[i, features_train_filled.ix[match_id, 'd%d_hero' % (p+1)]-1] = -1
        
print(X_pick.shape)
print(X_pick[0,:])

(97230, 112)
[ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
 -1.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.
  0.  0.  0.  0.]

In [246]:
# add X_pick to features_train_filled_dropped

X_pick_indexed = pd.DataFrame(X_pick, index = features_train_filled_dropped.index)
features_train_filled_ext = pd.concat([features_train_filled_dropped, X_pick_indexed], axis = 1, join_axes=[features_train_filled_dropped.index])

print(features_train_filled_ext.shape)
features_train_filled_ext

(97230, 203)

,start_time,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,r2_level,r2_xp,...,102,103,104,105,106,107,108,109,110,111
match_id,,,,,,,,,,,,,,,,,,,,,
0,1430198770,5,2098,1489,20,0,0,7,3,842,...,0,0,1,0,0,0,0,0,0,0
1,1430220345,4,1188,1033,9,0,1,12,4,1596,...,0,0,0,0,0,0,0,0,0,0
2,1430227081,4,1319,1270,22,0,0,12,3,1314,...,0,0,0,0,0,0,0,0,0,0
3,1430263531,4,1779,1056,14,0,0,5,2,539,...,0,0,0,0,0,0,0,0,0,0
4,1430282290,4,1431,1090,8,1,0,8,2,629,...,0,0,0,0,0,0,0,0,0,0
5,1430284186,5,1961,1461,19,0,1,6,2,441,...,0,0,0,0,0,0,0,0,0,0
8,1430293701,3,967,1136,7,1,0,8,4,1774,...,0,0,0,0,0,0,0,0,0,0
9,1430299335,5,2117,1252,16,0,0,6,3,1378,...,0,0,0,0,0,0,0,0,0,0
11,1430308974,5,1527,906,10,0,1,7,3,733,...,0,0,0,0,0,0,0,0,0,0
12,1430316105,5,1651,1060,14,0,1,10,3,951,...,0,0,0,0,0,0,0,0,0,0
14,1430325079,5,1988,1804,21,1,0,6,2,537,...,0,0,0,0,0,0,0,0,0,0
15,1430330210,3,819,763,12,0,2,9,2,488,...,0,0,0,0,0,0,0,0,0,1
17,1430331421,2,611,500,0,0,0,6,2,392,...,0,0,0,0,0,0,0,0,0,0
20,1430341277,3,739,585,4,0,0,11,5,2448,...,0,0,0,0,0,0,0,0,0,0
21,1430342692,2,430,642,1,0,1,5,2,668,...,0,0,0,0,0,0,0,0,0,0
22,1430342847,3,1221,1388,18,0,0,6,3,731,...,0,0,0,0,0,0,0,0,0,0
23,1430344863,3,786,1088,3,0,0,9,5,1842,...,0,0,0,0,0,0,0,0,0,0
25,1430352015,4,1435,694,5,0,1,4,2,551,...,0,0,0,0,0,0,0,0,0,0
26,1430354106,2,731,500,1,0,1,8,3,928,...,0,0,0,0,0,0,0,0,0,0
27,1430355047,4,1697,975,4,0,0,9,2,830,...,0,0,0,0,0,0,0,0,0,0
28,1430356392,4,1276,1259,9,1,1,8,4,1871,...,0,1,0,0,0,0,0,0,0,0
29,1430357535,2,625,789,1,0,0,7,3,1274,...,0,0,0,0,0,0,0,0,0,0
30,1430358429,5,2081,2187,19,0,0,9,4,1433,...,0,-1,0,0,0,0,0,0,0,1
31,1430363469,0,914,825,4,0,0,4,1,1686,...,0,0,0,0,0,0,0,-1,0,0
32,1430365431,5,1855,2035,35,0,0,11,3,741,...,0,0,0,0,0,0,0,0,0,-1
34,1430372971,3,802,592,1,0,1,7,2,363,...,0,0,0,0,0,0,0,1,0,0
35,1430373522,4,1170,1384,6,2,1,6,3,983,...,0,0,0,0,0,0,0,0,0,0
36,1430374551,4,1324,1338,15,0,0,11,4,1559,...,0,0,0,0,0,0,0,0,0,0
38,1430375522,4,1299,1218,23,0,0,6,4,1591,...,0,0,0,0,0,0,0,0,0,0
39,1430377785,4,1258,1706,21,1,0,6,5,1691,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114373,1450217420,5,1993,1510,21,0,0,4,4,1114,...,0,0,0,0,0,0,0,0,0,-1
114374,1450220370,5,1699,1575,17,1,1,8,4,1310,...,0,0,0,0,0,0,0,0,0,0
114375,1450220378,5,2258,1698,23,0,0,6,5,1912,...,0,0,0,0,0,0,0,0,0,-1
114376,1450221758,2,634,500,0,0,1,6,4,1289,...,0,0,0,0,0,0,0,0,0,0
114379,1450223876,2,548,671,3,0,0,9,5,2023,...,0,0,0,-1,0,0,0,0,0,0
114380,1450224353,3,891,1682,21,1,0,8,2,280,...,0,0,0,0,0,0,0,0,0,1
114381,1450225074,3,1682,1611,17,1,0,9,3,813,...,0,0,0,0,0,0,0,0,0,0
114382,1450225077,4,1538,1407,19,0,1,7,4,1390,...,0,0,0,1,0,0,0,0,0,0
114383,1450226303,3,1159,1004,5,1,1,7,5,2093,...,0,0,0,0,0,0,0,0,0,1
114384,1450227800,2,625,585,2,0,1,7,4,1355,...,0,0,0,1,0,0,0,0,0,1
114385,1450227829,4,1299,1271,19,0,0,10,5,1845,...,0,0,0,0,0,0,0,0,0,-1
114386,1450228956,3,912,1789,20,2,1,11,4,1669,...,0,0,0,0,0,0,0,0,0,0
114387,1450229215,4,1383,1603,23,0,0,7,2,400,...,0,0,0,0,0,0,0,0,0,0
114388,1450231917,2,763,991,0,1,0,10,4,1332,...,0,0,0,-1,0,0,0,-1,0,0
114389,1450233506,3,708,1172,0,2,0,6,3,1131,...,0,0,0,0,0,0,0,0,0,0
114390,1450242081,5,1930,1535,13,1,0,5,4,1288,...,0,0,0,0,0,0,0,0,0,0
114391,1450242546,3,549,942,6,1,0,11,5,2048,...,0,0,0,0,0,0,0,0,0,0
114392,1450244314,5,2387,2085,26,1,0,9,2,483,...,0,0,0,0,0,0,0,0,0,1
114394,1450247972,5,2017,1845,32,0,0,6,2,440,...,0,0,0,0,0,0,0,0,0,0
114395,1450248756,5,2160,2087,25,1,0,9,4,2182,...,0,0,0,-1,0,0,0,0,0,0
114396,1450249964,5,2038,1420,21,0,1,6,4,1737,...,0,0,0,0,0,0,0,0,0,1
114397,1450250562,4,1665,1788,30,0,0,9,5,1951,...,0,0,0,0,0,0,0,0,0,0
114399,1450258083,5,2049,1864,28,0,0,9,4,1509,...,0,0,0,0,0,0,0,0,0,0
114400,1450263508,5,2097,1910,24,1,1,14,3,800,...,0,0,0,0,0,0,0,0,0,0
114401,1450264638,2,730,1110,0,2,0,9,3,1054,...,0,0,0,1,0,0,0,0,0,-1
114402,1450265551,4,1706,1198,17,0,1,8,2,616,...,0,0,0,0,0,0,0,0,0,0
114403,1450277704,4,1793,1416,17,0,1,5,3,764,...,0,0,0,0,0,0,0,1,0,0
114404,1450291848,4,1399,540,1,0,0,5,4,1448,...,0,0,0,0,0,0,0,0,0,1
114405,1450292986,3,1135,766,6,0,2,6,5,1954,...,0,0,0,-1,0,0,0,0,0,0
114406,1450313370,3,1053,799,7,0,0,7,5,2097,...,0,0,0,-1,0,0,0,0,0,-1

In [261]:
# scale features_train_filled_ext

scaler_ext = StandardScaler().fit(features_train_filled_ext)
features_train_filled_ext_scaled = scaler_ext.transform(features_train_filled_ext)
print(features_train_filled_ext_scaled.shape)
print(features_train_filled_ext_scaled)

(97230, 203)
[[ -2.54436416e+00   1.40080818e+00   1.52597175e+00 ...,  -4.83865990e-03
    0.00000000e+00   8.46061344e-04]
 [ -2.54045236e+00   5.01313538e-01  -8.01392943e-02 ...,  -4.83865990e-03
    0.00000000e+00   8.46061344e-04]
 [ -2.53923104e+00   5.01313538e-01   1.51070097e-01 ...,  -4.83865990e-03
    0.00000000e+00   8.46061344e-04]
 ...,
 [  1.09874571e+00   5.01313538e-01   2.92266672e-01 ...,  -4.83865990e-03
    0.00000000e+00   1.64609695e+00]
 [  1.09895204e+00  -3.98181106e-01  -1.73682025e-01 ...,  -4.83865990e-03
    0.00000000e+00   8.46061344e-04]
 [  1.10264790e+00  -3.98181106e-01  -3.18408515e-01 ...,  -4.83865990e-03
    0.00000000e+00  -1.64440483e+00]]

In [250]:
# Using cross-validation folds from Part 1 (kf)
# learning linear_model.LogisticRegression on features_train_filled_ext_scaled

scores_lr_ext = np.zeros(5)
ix = 0

for C_reg in [10000, 100, 1, 0.01, 0.0001] :
    
    print("C_reg = ", C_reg)
    clf_lr_ext = LogisticRegression(penalty='l2', C = C_reg, random_state = 16)
    
    start_time = datetime.datetime.now()
    cv_scores_lr_ext = cross_val_score(clf_lr, features_train_filled_ext_scaled, np.ravel(targets_train), cv = kf, scoring='roc_auc')
    print ('Time elapsed:', datetime.datetime.now() - start_time)
    
    scores_lr_ext[ix] = cv_scores_lr_ext.mean()
    ix = ix + 1
    

print(scores_lr_ext)

C_reg =  10000
Time elapsed: 0:00:09.422539
C_reg =  100
Time elapsed: 0:00:09.185525
C_reg =  1
Time elapsed: 0:00:08.886509
C_reg =  0.01
Time elapsed: 0:00:08.987514
C_reg =  0.0001
Time elapsed: 0:00:08.846506
[ 0.74240927  0.74240927  0.74240927  0.74240927  0.74240927]

In [254]:
# check coefficients of the resulting model (=importances)

clf_lr_ext = LogisticRegression(penalty='l2', C = 0.01, random_state = 16)
clf_lr_ext.fit(features_train_filled_ext_scaled, np.ravel(targets_train))

print(np.shape(np.ravel(clf_lr_ext.coef_)))
print(np.shape(np.ravel([features_train_filled_ext.columns])))

coef_lr_ext = np.transpose(np.array([np.ravel([features_train_filled_ext.columns]), np.ravel(clf_lr_ext.coef_)]))
coef_lr_ext_df = pd.DataFrame(coef_lr_ext, columns = ('feature', 'coef')); coef_lr_ext_df
coef_lr_ext_df_sorted = coef_lr_ext_df.sort_values(by = 'coef', ascending=False)
print(coef_lr_ext_df_sorted.head(40))

(203,)
(203,)
                 feature       coef
18                 r3_lh   0.227213
25                 r4_lh   0.226452
11                 r2_lh     0.2225
4                  r1_lh   0.214667
32                 r5_lh   0.210396
3                r1_gold     0.1988
10               r2_gold    0.19525
31               r5_gold   0.172595
157                   66   0.167046
24               r4_gold   0.163673
17               r3_gold   0.161512
97                     6   0.142226
147                   56   0.126632
161                   70   0.125203
132                   41   0.105924
23                 r4_xp  0.0954405
118                   27  0.0914755
159                   68  0.0838293
2                  r1_xp  0.0832089
16                 r3_xp  0.0798016
112                   21   0.076106
30                 r5_xp  0.0707733
192                  101  0.0684767
9                  r2_xp  0.0646372
190                   99  0.0600195
98                     7   0.056829
69             d5_deaths  0.0556379
163                   72  0.0519121
35              r5_items  0.0511452
152                   61  0.0501595
160                   69  0.0498128
142                   51  0.0494293
0             start_time  0.0485671
41             d1_deaths  0.0481095
122                   31  0.0468071
21              r3_items  0.0467382
101                   10  0.0464063
175                   84  0.0462185
200                  109  0.0450216
86   dire_tpscroll_count  0.0436643

In [262]:
# prepare test data
# by now we have features_test_filled (filled with 0 instead of NAs)
# we need to remove categorical values, add "мешок слов" features and scale

# drop categorical variables

features_test_filled_dropped = features_test_filled.drop(['lobby_type', 'r1_hero', 'r2_hero', 'r3_hero', 'r4_hero', 'r5_hero',
                                                            'd1_hero', 'd2_hero', 'd3_hero', 'd4_hero', 'd5_hero'], axis = 1)
print('features_test_filled_dropped.shape = ', features_test_filled_dropped.shape)

# add "мешок слов" features instead

N = 112
X_pick_test = np.zeros((features_test_filled.shape[0], N))

for i, match_id in enumerate(features_test_filled.index):
    for p in range(5):
        X_pick_test[i, features_test_filled.ix[match_id, 'r%d_hero' % (p+1)]-1] = 1
        X_pick_test[i, features_test_filled.ix[match_id, 'd%d_hero' % (p+1)]-1] = -1
        
print('X_pick_test.shape = ', X_pick_test.shape)
print('X_pick_test[0,:] = ', X_pick_test[0,:])

X_pick_test_indexed = pd.DataFrame(X_pick_test, index = features_test_filled_dropped.index)
features_test_filled_ext = pd.concat([features_test_filled_dropped, X_pick_test_indexed], axis = 1, join_axes=[features_test_filled_dropped.index])

print('features_test_filled_ext.shape = ', features_test_filled_ext.shape)
print('features_test_filled_ext = ', features_test_filled_ext)

# scale

features_test_filled_ext_scaled = scaler_ext.transform(features_test_filled_ext)
print('features_test_filled_ext_scaled.shape = ', features_test_filled_ext_scaled.shape)
print('features_test_filled_ext_scaled = ', features_test_filled_ext_scaled)

features_test_filled_dropped.shape =  (17177, 91)
X_pick_test.shape =  (17177, 112)
X_pick_test[0,:] =  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0. -1.  0.  0.  0.  0.  0. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.
  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.
  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.
  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.]
features_test_filled_ext.shape =  (17177, 203)
features_test_filled_ext =            start_time  r1_level  r1_xp  r1_gold  r1_lh  r1_kills  r1_deaths  \
match_id
6         1430287923         4   1103     1089      8         0          1
7         1430293357         2    556      570      1         0          0
10        1430301774         2    751      808      1         0          0
13        1430323933         3    708      903      1         1          1
16        1430331112         4   1259      661      4         0          0
18        1430334264         5   2067     1549     15         0          0
19        1430334995         4   1862     1487     24         0          1
24        1430349466         5   1991     1983     19         2          0
33        1430366484         2    517      500      0         0          1
37        1430375099         3   1060      691      5         0          0
41        1430378434         4   1760     1162     16         0          1
42        1430379583         1    141      619      1         0          0
55        1430393467         2    629      557      0         0          0
60        1430398436         2    572      828      5         0          0
62        1430399788         3   1567     1823     30         0          0
63        1430401076         5   2231     2044     22         0          0
64        1430402407         4   1435     1173     17         0          1
71        1430408743         5   1848     1497     24         0          1
72        1430408794         2    487      499      0         0          0
83        1430421091         2    286      558      0         0          0
85        1430421840         2    892      737      1         0          0
89        1430424264         5   1945     2112     25         2          0
92        1430427279         3   1017     1421     20         0          1
100       1430432885         2    431      984      0         1          0
102       1430435117         3    777      541      1         0          0
108       1430441463         2    454      741      1         0          1
111       1430442629         2    672      537      2         0          0
126       1430455303         2    949      895      2         1          0
130       1430459074         2    464      588      2         0          1
140       1430466608         4   1447     1801     30         0          0
...              ...       ...    ...      ...    ...       ...        ...
114165    1450131598         4   1373     1426     12         1          0
114168    1450132288         3    686      633      0         0          0
114171    1450133142         4   1831     1086     12         0          0
114183    1450135777         2    635      696      4         0          1
114188    1450136846         4   1190     1587     25         0          0
114192    1450137508         2    364      663      4         1          0
114195    1450139129         2    699      663      0         0          0
114202    1450140803         5   2109     1814     21         1          0
114209    1450141777         3   1081      898      3         0          0
114211    1450142038         3   1245     1410     20         0          0
114217    1450143728         5   2246     2287     26         1          0
114232    1450148011         3   1080     1352     15         1          1
114236    1450149079         3    765      775      5         0          1
114238    1450149573         4   1449     1670     22         1          0
114242    1450150528         3   1099     1268     12         0          1
114247    1450152049         3   1210     1439     19         0          0
114285    1450162146         5   1724     1411     22         0          0
114286    1450162461         4   1556      852      9         0          0
114314    1450171844         5   1752     1212     14         0          1
114327    1450179554         3    869      912      3         1          0
114330    1450181136         2    694      638      3         0          1
114337    1450185543         2    763     1066      2         2          1
114348    1450190796         4   1631     1289     19         0          0
114349    1450190965         5   1841     1682     10         1          0
114361    1450203051         5   2176     1980     26         0          0
114369    1450212780         5   2054     1941     27         0          1
114377    1450222875         3    748      605      1         0          0
114378    1450223593         2    575      499      0         0          0
114393    1450244771         4   1844     1176      8         1          2
114398    1450255429         4   1215     1305     13         0          0

          r1_items  r2_level  r2_xp ...   102  103  104  105  106  107  108  \
match_id                            ...
6                9         3   1183 ...     0    0    0    0    0    0    0
7                9         4   1194 ...     0    0    0    0    0    0    0
10              13         2    421 ...     0    0    0    0    0    0    0
13              11         2    672 ...     0    0    0    0    0    0    0
16               9         5   1703 ...     0    0    0    0    0    0    0
18               8         4   1258 ...     0    0    0    0    0    0    0
19               5         3    894 ...     0    0    0    0    0    0    0
24              10         4   1498 ...     0    0    0    1    0    0    0
33               9         4   1585 ...     0    0    0    0    0    0    0
37               6         4   1214 ...     0    0    0    0    0    0    0
41               7         2    505 ...     0    0    0    0    0    0    0
42              10         3   1152 ...     0    0    0    0    0    0    0
55               1         4   1530 ...     0    0    0    0    0    0    0
60               4         4   1622 ...     0    0    0    0    0    0    0
62               4         2    474 ...     0    0    0    0    0    0    0
63               7         4   1470 ...     0   -1    0    0    0    0    0
64               4         4   1655 ...     0    0    0    0    0    0    0
71               9         3   1032 ...     0   -1    0    0    0    0    0
72               8         5   2017 ...     0    0    0    0    0    0    0
83               8         3    681 ...     0    0    0    0    0    0    0
85               7         2    621 ...     0    0    0    0    0    0    0
89              13         3    800 ...     0    0    0    0    0    0    0
92               9         4   1190 ...     0    0    0    0    0    0    0
100              6         4   2273 ...     0    0    0    0    0    0    0
102              8         4   1200 ...     0   -1    0    0    0    0    0
108             10         2    582 ...     0    0    0    0    0    0    0
111              7         2    348 ...     0    0   -1    0    0    0    0
126              4         4   1532 ...     0    0    0    0    0    0    0
130              8         3    879 ...     0    0    0    0    0    0    0
140              6         5   2161 ...     0    0    0    0    0    0    0
...            ...       ...    ... ...   ...  ...  ...  ...  ...  ...  ...
114165          14         5   1923 ...     0    0    0    0    0    0    0
114168           8         4   1574 ...     0    0    0   -1    0    0    0
114171           7         4   1588 ...     0    0    0    0    0    0    0
114183           9         3   1049 ...     0    0    0    0    0    0    0
114188          10         2    419 ...     0    0    0    1    0    0    0
114192          11         4   1737 ...     0    0    0    0    0    0    0
114195           9         3    940 ...     0    0    0    0    0    0    0
114202           9         4   1437 ...     0    0    0   -1    0    0    0
114209           8         3   1356 ...     0    0    0   -1    0    0    0
114211           9         3   1118 ...     0    0    0    0    0    0    0
114217           8         2    392 ...    -1    0    0    0    0    0    0
114232           7         3    870 ...     0    0    0    0    0    0    0
114236           9         4   1062 ...     0    0    0    0    0    0    0
114238           6         2    372 ...     0    0    0    0    0    0    0
114242          10         4   1289 ...     0    0    0    1    0    0    0
114247           7         5   1870 ...     0    0    0    0    0    0    0
114285          12         3    887 ...     0    0    0    0    0    0    0
114286           8         4   1290 ...     0    0    0    0    0    0    0
114314           9         4   1249 ...     0    0    0    1    0    0    0
114327          10         5   2042 ...     0    0    0    0    0    0    0
114330           7         4   1554 ...     0    0    0   -1    0    0    0
114337           7         3    999 ...     0    0    0    0    0    0    0
114348           6         4   1731 ...     0    0    0    0    0    0    0
114349          14         3   1014 ...     0    0    0    1    0    0    0
114361           8         3    748 ...     0    0   -1    0    0    0    0
114369           8         4   1460 ...     0    0    0    0    0    0    0
114377          12         3   1130 ...     0    0    0    0    0    0    0
114378           8         3    697 ...     0    0    0   -1    0    0    0
114393           8         3   1013 ...     0    0    0    0    0    0    0
114398          10         5   1867 ...     0    0    0    0    0    0    0

          109  110  111
match_id
6           0    0    0
7           0    0    0
10          0    0    1
13         -1    0    0
16          0    0    0
18          0    0    0
19          0    0    1
24          0    0    0
33          0    0    0
37          0    0    0
41          0    0    0
42          0    0    0
55          0    0    0
60          0    0    0
62          0    0    0
63          0    0    0
64          0    0    0
71          0    0    0
72          1    0    0
83          0    0    0
85          0    0    0
89         -1    0    0
92          0    0    1
100         0    0    0
102         0    0    0
108         0    0    0
111         0    0    0
126         0    0    0
130         0    0    0
140         0    0    0
...       ...  ...  ...
114165      0    0    0
114168      1    0    0
114171      0    0    0
114183      0    0    0
114188      0    0    0
114192      0    0    0
114195      0    0    0
114202      0    0    0
114209      0    0   -1
114211      0    0    0
114217      0    0    0
114232      0    0    0
114236      0    0    0
114238      0    0    1
114242      0    0    0
114247      0    0    0
114285      0    0    1
114286      0    0    0
114314      0    0   -1
114327      0    0    1
114330      0    0    1
114337      0    0    0
114348      0    0   -1
114349      0    0   -1
114361      0    0   -1
114369      0    0    0
114377      0    0   -1
114378      0    0    0
114393      0    0   -1
114398      0    0    1

[17177 rows x 203 columns]
features_test_filled_ext_scaled.shape =  (17177, 203)
features_test_filled_ext_scaled =  [[ -2.52819967e+00   5.01313538e-01  -2.30160655e-01 ...,  -4.83865990e-03
    0.00000000e+00   8.46061344e-04]
 [ -2.52721443e+00  -1.29767575e+00  -1.19559224e+00 ...,  -4.83865990e-03
    0.00000000e+00   8.46061344e-04]
 [ -2.52568833e+00  -1.29767575e+00  -8.51425585e-01 ...,  -4.83865990e-03
    0.00000000e+00   1.64609695e+00]
 ...,
 [  1.08637028e+00  -1.29767575e+00  -1.16205805e+00 ...,  -4.83865990e-03
    0.00000000e+00   8.46061344e-04]
 [  1.09021010e+00   5.01313538e-01   1.07767262e+00 ...,  -4.83865990e-03
    0.00000000e+00  -1.64440483e+00]
 [  1.09214252e+00   5.01313538e-01  -3.24854502e-02 ...,  -4.83865990e-03
    0.00000000e+00   1.64609695e+00]]

In [263]:
#make predictions for test data

pred_lr = clf_lr_ext.predict_proba(features_test_filled_ext_scaled)[:, 1]
print(pred_lr.shape)
pred_lr

#create output array and write it to .csv
output_lr = np.array([features_test_filled_ext.index.values, pred_lr])
#print(output.shape)
output_lr = np.transpose(output_lr)
print(output_lr.shape)
np.savetxt('output_lr_2.csv', output_lr, fmt='%.10f', header = 'match_id, radiant_win', delimiter=',')

(17177,)
(17177, 2)

In [264]:
# ______________________________________________________________________________________________________________________________________________________
# improving the score
# let's use gradient boosting to features_test_filled_ext

scores_gb_1 = np.zeros(3)
ix = 0

for n_trees in [30] :
    
    print("n_trees = ", n_trees)
    clf_gb_1 = GradientBoostingClassifier(n_estimators = n_trees, verbose = True, random_state = 16, learning_rate = 0.1, max_depth = 3)
    
    start_time = datetime.datetime.now()
    cv_scores_gb_1 = cross_val_score(clf_gb_1, features_train_filled_ext, np.ravel(targets_train), cv = kf, scoring='roc_auc')
    print ('Time elapsed:', datetime.datetime.now() - start_time)
    
    scores_gb_1[ix] = cv_scores_gb_1.mean()
    ix = ix + 1
    

print(scores_gb_1)

n_trees =  30
      Iter       Train Loss   Remaining Time
         1           1.3785            1.17m
         2           1.3730            1.10m
         3           1.3681            1.04m
         4           1.3635           59.30s
         5           1.3588            1.00m
         6           1.3546           57.06s
         7           1.3500           53.22s
         8           1.3459           49.67s
         9           1.3420           46.11s
        10           1.3384           43.02s
        20           1.3087           20.13s
        30           1.2887            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3785           53.42s
         2           1.3729           52.25s
         3           1.3681           50.08s
         4           1.3633           48.49s
         5           1.3585           46.04s
         6           1.3538           43.77s
         7           1.3494           41.76s
         8           1.3452           39.80s
         9           1.3411           37.99s
        10           1.3373           36.14s
        20           1.3077           18.06s
        30           1.2879            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3784           53.65s
         2           1.3728           52.77s
         3           1.3677           53.88s
         4           1.3632           51.25s
         5           1.3583           48.09s
         6           1.3536           45.46s
         7           1.3492           43.19s
         8           1.3454           41.52s
         9           1.3413           39.52s
        10           1.3374           37.43s
        20           1.3076           18.08s
        30           1.2874            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3789           53.04s
         2           1.3732           51.44s
         3           1.3684           49.54s
         4           1.3640           47.75s
         5           1.3594           45.94s
         6           1.3548           43.73s
         7           1.3502           41.63s
         8           1.3458           39.59s
         9           1.3418           37.72s
        10           1.3380           35.73s
        20           1.3082           17.83s
        30           1.2875            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3783           56.00s
         2           1.3725           52.74s
         3           1.3675           50.28s
         4           1.3629           48.43s
         5           1.3578           46.24s
         6           1.3536           44.49s
         7           1.3493           42.30s
         8           1.3451           40.05s
         9           1.3411           38.11s
        10           1.3372           36.18s
        20           1.3075           17.91s
        30           1.2874            0.00s
Time elapsed: 0:04:35.561761
[ 0.68891494  0.          0.        ]

In [291]:
# let's sum up features of heros per team

X_agg = pd.DataFrame(index = features_train_filled_ext.index)
#X_agg['r_level'] = features_train_filled_ext.ix[:,('r1_level', 'r2_level', 'r3_level', 'r4_level', 'r5_level')].sum(axis = 1)
#X_agg['d_level'] = features_train_filled_ext.ix[:,('d1_level', 'd2_level', 'd3_level', 'd4_level', 'd5_level')].sum(axis = 1)

X_agg['r_level'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['r_xp'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['r_gold'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['r_lh'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['r_kills'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['r_deaths'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['r_items'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['d_level'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['d_xp'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['d_gold'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['d_lh'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['d_kills'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['d_deaths'] = np.zeros(features_train_filled_ext.shape[0])
X_agg['d_items'] = np.zeros(features_train_filled_ext.shape[0])


for p in range(5):
    X_agg['r_level'] = X_agg['r_level'] + features_train_filled.ix[:, 'r%d_level' % (p+1)]
    X_agg['r_xp'] = X_agg['r_xp'] + features_train_filled.ix[:, 'r%d_xp' % (p+1)]
    X_agg['r_gold'] = X_agg['r_gold'] + features_train_filled.ix[:, 'r%d_gold' % (p+1)]
    X_agg['r_lh'] = X_agg['r_lh'] + features_train_filled.ix[:, 'r%d_lh' % (p+1)]
    X_agg['r_kills'] = X_agg['r_kills'] + features_train_filled.ix[:, 'r%d_kills' % (p+1)]
    X_agg['r_deaths'] = X_agg['r_deaths'] + features_train_filled.ix[:, 'r%d_deaths' % (p+1)]
    X_agg['r_items'] = X_agg['r_items'] + features_train_filled.ix[:, 'r%d_items' % (p+1)]
    X_agg['d_level'] = X_agg['d_level'] + features_train_filled.ix[:, 'd%d_level' % (p+1)]
    X_agg['d_xp'] = X_agg['d_xp'] + features_train_filled.ix[:, 'd%d_xp' % (p+1)]
    X_agg['d_gold'] = X_agg['d_gold'] + features_train_filled.ix[:, 'd%d_gold' % (p+1)]
    X_agg['d_lh'] = X_agg['d_lh'] + features_train_filled.ix[:, 'd%d_lh' % (p+1)]
    X_agg['d_kills'] = X_agg['d_kills'] + features_train_filled.ix[:, 'd%d_kills' % (p+1)]
    X_agg['d_deaths'] = X_agg['d_deaths'] + features_train_filled.ix[:, 'd%d_deaths' % (p+1)]
    X_agg['d_items'] = X_agg['d_items'] + features_train_filled.ix[:, 'd%d_items' % (p+1)]


print(X_agg['r_level'])
print(features_train_filled.ix[:, 'r%d_level' % (p+1)])

match_id
0         19
1         17
2         18
3         16
4         16
5         16
8         16
9         15
11        16
12        18
14        17
15        15
17        14
20        17
21        14
22        18
23        18
25        16
26        17
27        17
28        17
29        16
30        16
31         5
32        17
34        17
35        19
36        17
38        17
39        17
          ..
114373    17
114374    17
114375    17
114376    19
114379    17
114380    16
114381    17
114382    17
114383    17
114384    16
114385    19
114386    16
114387    19
114388    17
114389    18
114390    17
114391    18
114392    18
114394    16
114395    18
114396    18
114397    19
114399    19
114400    18
114401    16
114402    16
114403    17
114404    17
114405    16
114406    19
Name: r_level, dtype: float64
match_id
0         3
1         2
2         3
3         3
4         4
5         3
8         2
9         2
11        1
12        3
14        2
15        2
17        2
20        3
21        4
22        5
23        2
25        2
26        4
27        4
28        4
29        3
30        3
31        1
32        2
34        5
35        3
36        2
38        3
39        2
         ..
114373    3
114374    3
114375    2
114376    3
114379    4
114380    3
114381    2
114382    2
114383    2
114384    4
114385    3
114386    4
114387    3
114388    3
114389    5
114390    2
114391    2
114392    3
114394    2
114395    3
114396    3
114397    2
114399    5
114400    3
114401    5
114402    3
114403    3
114404    2
114405    5
114406    4
Name: r5_level, dtype: int64

In [292]:
# drop corresponding "per hero" variables; add "per team" ones; scale

print(features_train_filled_ext.shape)
features_train_filled_ext_agg = features_train_filled_ext

for p in range(5):
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['r%d_level' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['r%d_xp' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['r%d_gold' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['r%d_lh' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['r%d_kills' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['r%d_deaths' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['r%d_items' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['d%d_level' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['d%d_xp' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['d%d_gold' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['d%d_lh' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['d%d_kills' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['d%d_deaths' % (p+1)], axis = 1)
    features_train_filled_ext_agg = features_train_filled_ext_agg.drop(['d%d_items' % (p+1)], axis = 1)

print(features_train_filled_ext_agg.shape)

# add variables from X_agg

X_agg_indexed = pd.DataFrame(X_agg, index = features_train_filled_ext_agg.index)
features_train_filled_ext_agg = pd.concat([features_train_filled_ext_agg, X_agg_indexed], axis = 1, join_axes=[features_train_filled_ext_agg.index])

print('features_train_filled_ext_agg.shape = ', features_train_filled_ext_agg.shape)

#scale

scaler_agg = StandardScaler().fit(features_train_filled_ext_agg)
features_train_filled_ext_agg_scaled = scaler_agg.transform(features_train_filled_ext_agg)
print(features_train_filled_ext_agg_scaled.shape)
print(features_train_filled_ext_agg_scaled)

(97230, 203)
(97230, 133)
features_train_filled_ext_agg.shape =  (97230, 147)
(97230, 147)
[[-2.54436416 -0.84990227  1.18270291 ..., -0.50051541 -1.11143739
  -1.35317091]
 [-2.54045236 -0.28763079  1.18270291 ...,  0.13061383 -0.4664654
  -0.08777596]
 [-2.53923104  1.74611708 -0.84552088 ..., -0.50051541  0.1785066
   0.07039841]
 ...,
 [ 1.09874571  0.35838324 -0.84552088 ..., -0.50051541 -0.4664654
  -0.24595033]
 [ 1.09895204 -0.59867459 -0.84552088 ...,  0.76174306 -0.4664654
  -0.56229906]
 [ 1.1026479  -0.76615971  1.18270291 ...,  0.13061383  0.82347859
   0.07039841]]

In [293]:
# Using cross-validation folds from Part 1 (kf)
# learning linear_model.LogisticRegression on features_train_filled_ext_scaled

scores_lr_agg = np.zeros(5)
ix = 0

for C_reg in [10000, 100, 1, 0.01, 0.0001] :
    
    print("C_reg = ", C_reg)
    clf_lr_agg = LogisticRegression(penalty='l2', C = C_reg, random_state = 16)
    
    start_time = datetime.datetime.now()
    cv_scores_lr_agg = cross_val_score(clf_lr_agg, features_train_filled_ext_agg_scaled, np.ravel(targets_train), cv = kf, scoring='roc_auc')
    print ('Time elapsed:', datetime.datetime.now() - start_time)
    
    scores_lr_agg[ix] = cv_scores_lr_agg.mean()
    ix = ix + 1
    

print(scores_lr_agg)

C_reg =  10000
Time elapsed: 0:00:13.845792
C_reg =  100
Time elapsed: 0:00:13.916796
C_reg =  1
Time elapsed: 0:00:15.249872
C_reg =  0.01
Time elapsed: 0:00:14.021802
C_reg =  0.0001
Time elapsed: 0:00:06.577377
[ 0.7519592   0.75195919  0.75195962  0.75197595  0.74690676]

In [294]:
# check coefficients of the resulting model (=importances)

clf_lr_agg = LogisticRegression(penalty='l2', C = 0.01, random_state = 16)
clf_lr_agg.fit(features_train_filled_ext_agg_scaled, np.ravel(targets_train))

print(np.shape(np.ravel(clf_lr_agg.coef_)))
print(np.shape(np.ravel([features_train_filled_ext_agg.columns])))

coef_lr_agg = np.transpose(np.array([np.ravel([features_train_filled_ext_agg.columns]), np.ravel(clf_lr_agg.coef_)]))
coef_lr_agg_df = pd.DataFrame(coef_lr_agg, columns = ('feature', 'coef')); coef_lr_ext_df
coef_lr_agg_df_sorted = coef_lr_agg_df.sort_values(by = 'coef', ascending=False)
print(coef_lr_agg_df_sorted.head(40))

(147,)
(147,)
                         feature       coef
135                       r_gold   0.319701
136                         r_lh   0.288239
87                            66   0.167247
27                             6   0.143202
77                            56   0.127321
91                            70   0.125461
145                     d_deaths   0.114217
62                            41   0.106166
139                      r_items   0.102376
134                         r_xp   0.101712
48                            27  0.0916218
89                            68  0.0838099
42                            21  0.0764511
122                          101  0.0684644
120                           99  0.0603342
28                             7  0.0569967
93                            72  0.0549966
82                            61  0.0507082
144                      d_kills  0.0498371
90                            69  0.0496671
72                            51  0.0490124
0                     start_time  0.0484482
52                            31  0.0468206
105                           84  0.0461793
31                            10   0.045577
130                          109  0.0454504
16           dire_tpscroll_count  0.0435778
21                             0  0.0384274
114                           93  0.0378786
60                            39  0.0378285
111                           90  0.0367256
102                           81  0.0363465
7    radiant_flying_courier_time  0.0356335
97                            76  0.0339118
9            radiant_boots_count  0.0316172
58                            37  0.0315507
69                            48  0.0313749
20          dire_first_ward_time  0.0310241
26                             5   0.030405
113                           92  0.0283689

In [ ]:
# prepare test data
# we've updated test set with мешок слов - features_test_filled_ext

# let's sum up features of heros per team - for TEST data

X_agg_test = pd.DataFrame(index = features_test_filled_ext.index)

X_agg_test['r_level'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['r_xp'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['r_gold'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['r_lh'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['r_kills'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['r_deaths'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['r_items'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['d_level'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['d_xp'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['d_gold'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['d_lh'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['d_kills'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['d_deaths'] = np.zeros(features_test_filled_ext.shape[0])
X_agg_test['d_items'] = np.zeros(features_test_filled_ext.shape[0])


for p in range(5):
    X_agg_test['r_level'] = X_agg_test['r_level'] + features_test_filled_ext.ix[:, 'r%d_level' % (p+1)]
    X_agg_test['r_xp'] = X_agg_test['r_xp'] + features_test_filled_ext.ix[:, 'r%d_xp' % (p+1)]
    X_agg_test['r_gold'] = X_agg_test['r_gold'] + features_test_filled_ext.ix[:, 'r%d_gold' % (p+1)]
    X_agg_test['r_lh'] = X_agg_test['r_lh'] + features_test_filled_ext.ix[:, 'r%d_lh' % (p+1)]
    X_agg_test['r_kills'] = X_agg_test['r_kills'] + features_test_filled_ext.ix[:, 'r%d_kills' % (p+1)]
    X_agg_test['r_deaths'] = X_agg_test['r_deaths'] + features_test_filled_ext.ix[:, 'r%d_deaths' % (p+1)]
    X_agg_test['r_items'] = X_agg_test['r_items'] + features_test_filled_ext.ix[:, 'r%d_items' % (p+1)]
    X_agg_test['d_level'] = X_agg_test['d_level'] + features_test_filled_ext.ix[:, 'd%d_level' % (p+1)]
    X_agg_test['d_xp'] = X_agg_test['d_xp'] + features_test_filled_ext.ix[:, 'd%d_xp' % (p+1)]
    X_agg_test['d_gold'] = X_agg_test['d_gold'] + features_test_filled_ext.ix[:, 'd%d_gold' % (p+1)]
    X_agg_test['d_lh'] = X_agg_test['d_lh'] + features_test_filled_ext.ix[:, 'd%d_lh' % (p+1)]
    X_agg_test['d_kills'] = X_agg_test['d_kills'] + features_test_filled_ext.ix[:, 'd%d_kills' % (p+1)]
    X_agg_test['d_deaths'] = X_agg_test['d_deaths'] + features_test_filled_ext.ix[:, 'd%d_deaths' % (p+1)]
    X_agg_test['d_items'] = X_agg_test['d_items'] + features_test_filled_ext.ix[:, 'd%d_items' % (p+1)]


print(X_agg['r_level'])
print(features_train_filled.ix[:, 'r%d_level' % (p+1)])



print(features_test_filled_ext.shape)
features_test_filled_ext_agg = features_test_filled_ext

for p in range(5):
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['r%d_level' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['r%d_xp' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['r%d_gold' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['r%d_lh' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['r%d_kills' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['r%d_deaths' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['r%d_items' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['d%d_level' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['d%d_xp' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['d%d_gold' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['d%d_lh' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['d%d_kills' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['d%d_deaths' % (p+1)], axis = 1)
    features_test_filled_ext_agg = features_test_filled_ext_agg.drop(['d%d_items' % (p+1)], axis = 1)

print(features_test_filled_ext_agg.shape)

# add variables from X_agg

X_agg_indexed = pd.DataFrame(X_agg, index = features_train_filled_ext_agg.index)
features_train_filled_ext_agg = pd.concat([features_train_filled_ext_agg, X_agg_indexed], axis = 1, join_axes=[features_train_filled_ext_agg.index])

print('features_train_filled_ext_agg.shape = ', features_train_filled_ext_agg.shape)

#scale

scaler_agg = StandardScaler().fit(features_train_filled_ext_agg)
features_train_filled_ext_agg_scaled = scaler_agg.transform(features_train_filled_ext_agg)
print(features_train_filled_ext_agg_scaled.shape)
print(features_train_filled_ext_agg_scaled)